/**
 * contexts/LangContext.jsx — 100% bilingual EN / RU
 * New keys: seeMore, seeLess, sort, filterBy, filterByVoter,
 *           noVoters, selectVoters, sortMostLikes, sortMostDislikes
 */
import { createContext, useContext, useState } from "react";

const T = {
  en: {
    appName: "Pickmatch",
    login: "Log in",
    loggedInAs: "Logged in as @{username}",
    register: "Sign up",
    logout: "Log out",
    dashboard: "My Albums",
    createAlbum: "New Album",

    email: "Email",
    username: "Username",
    password: "Password",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "No account yet?",
    loginTitle: "Welcome back",
    loginSubtitle: "Sign in to continue",
    registerTitle: "Create account",
    registerSubtitle: "Join Pickmatch — it's free",

    albumTitle: "Album title",
    albumDescription: "Description (optional)",
    uploadPhotos: "Upload photos",
    updatePhoto: "Update photo",
    addPhoto: "Add photo",
    removePhoto: "Remove photo",
    uploadDrag: "Drag & drop photos here, or click to browse",
    uploadHint: "JPEG, PNG, WebP",
    maxFileSize: "max 50 MB per file",
    albumTitlePlaceholder: "My Summer Shoot 2024",
    albumDescriptionPlaceholder: "Tell voters what this album is about…",
    publicAccess: "Public access",
    publicAccessHint: "Allow voters to see analytics",
    uploadRejected: "Some files were rejected (too large or wrong format)",
    uploadFailed: "Upload failed",
    retryUpload: "Retry upload",
    removeUpload: "Remove upload",
    enterAlbumTitle: "Please enter a title",
    uploadAtLeastOne: "Please upload at least one photo or video",
    albumCreated: "Album created!",
    creatingAlbum: "Creating album…",
    createAlbumBtn: "Create Album",
    inviteLink: "Invite Link",
    copyLink: "Copy",
    copied: "Copied!",
    myAlbums: "My Albums",
    noAlbums: "No albums yet — create your first one",
    photos: "photos",
    votes: "votes",
    viewAnalytics: "Results",
    deleteAlbum: "Delete",
    albumDeleted: "Deleted",
    albumNotFound: "Album not found",
    sharedWithMe: "Shared with me",
    sharedBy: "Shared by",
    shareAlbum: "Share album",
    shareWithUser: "Share with user (username or email)",
    shareSuccess: "Album shared",
    revokeAccess: "Revoke access",
    sharedAccess: "Shared access",
    noSharedAlbums: "No albums shared with you yet",

    swipeHint: "Swipe right to like · left to dislike",
    allDone: "You've rated all photos!",
    viewResults: "See results",
    swipeRemaining: "left",

    // New: expandable description
    seeMore: "See more",
    seeLess: "See less",

    // Analytics
    winner: "Winner",
    winnerBadge: "Winner",
    likes: "Likes",
    dislikes: "Dislikes",
    totalVotes: "Votes",
    likeRate: "Like rate",
    globalLikeRate: "Global like rate",
    uniqueVoters: "Voters",
    noVotes: "No votes yet",
    analyticsTitle: "All photos",
    backToAlbums: "My albums",
    // Sort & filter (button labels)
    sort: "Sort",
    filterBy: "Filter",
    // Sort sheet options
    sortMostLikes: "Most Likes",
    sortMostDislikes: "Most Dislikes",
    // View toggle inside sort sheet
    gridView: "Grid",
    listView: "List",
    // Analytics share-link sheet
    shareAnalytics: "Share analytics",
    shareAnalyticsHint: "Anyone with this link can view this album's results after signing in.",
    shareLinkCopied: "Link copied",
    shareLinkError: "Couldn't load the link. Try again.",
    linkManagement: "Link management",
    regenerateLink: "Regenerate link",
    regenerateLinkConfirm: "The old link will stop working immediately. Continue?",
    regenerateLinkDone: "New link generated",
    regenerateLinkFailed: "Couldn't regenerate link",
    needAccessTitle: "Access required",
    needAccessBody: "The link is invalid or has expired. Ask the album owner to share a new one.",
    // Filter sheet
    filterByVoter: "Filter by voter",
    noVoters: "No voters yet",
    selectVoters: "Select voters to filter",
    clearFilter: "Clear",
    applyFilter: "Apply",
    // Kept for backwards compat
    sortBy: "Sort by",
    sortLikesDesc: "Most liked",
    sortLikesAsc: "Least liked",
    sortDislikesDesc: "Most disliked",
    filterAll: "All",
    filterLiked: "Liked only",
    filterDisliked: "Disliked only",
    views: "Views",
    voters: "Voters",
    reactions: "Reactions",
    noReactions: "No reactions yet",
    share: "Share",

    heroTitle: "Pick the best photo",
    heroSubtitle: "Swipe right to like, left to pass. Easier like never before!",
    getStarted: "Get started",
    howItWorks: "How it works",
    step1Title: "Upload your album",
    step1Desc: "Add your photos and get an invite link.",
    step2Title: "Share & collect votes",
    step2Desc: "Send the link to your audience.",
    step3Title: "Discover the winner",
    step3Desc: "The photo with the most likes wins!",

    errorGeneric: "Something went wrong. Please try again.",
    errorNotFound: "Page not found",
    errorAlbumNotFound: "Album not found or link has expired",

    notifications: "Notifications",
    replies: "Replies",
    inbox: "Inbox",
    inboxDetails: "Activity and notifications",
    allCaughtUp: "You're all caught up!",
    noNewNotifs: "No new notifications right now.",
    Comments: "Comments",
    recentlyVisited: "Recently Visited",
    vote: "Vote",
    revote: "Vote again",
    noRecentAlbums: "Albums you visit will appear here",
    viewMyComments: "my thread",
    // Dashboard carousel / expanded view
    seeAll: "See all",
    searchAlbums: "Search albums",
    noSearchResults: "No albums match your search",
    sortNewest: "Newest",
    sortAlphabetical: "A–Z",
    sortMostVotes: "Most votes",
    sortMostRecent: "Most recent",
    rememberMe: "Remember me",
    forgotPassword: "Forgot Password?",
    backToLogin: "Back to login",
    resetPassword: "Reset Password",
    newPassword: "New Password",
    verifyEmailTitle: "Verify your email",
    verifyEmailCode: "Enter Code",
    verifyAccountBtn: "Verify Account",
    resendCode: "Didn't receive a code? Resend",
    resendCodeTimer: "Resend code in ",
    passwordStrength: "Password Strength",
    strengthWeak: "Weak",
    strengthMedium: "Medium",
    strengthStrong: "Strong",
    reqMinLength: "At least 8 characters",
    reqUppercase: "At least 1 uppercase letter",
    reqSpecial: "At least 1 special character",
    notifCommentPhoto: "commented on a photo from the album",
    notifLikedComment: "liked your comment",
    notifVotedAlbum: "voted in your album",
    notifRepliedComment: "replied to your comment",
    privateAlbumThreadHint: "This is a private album. You can only see your own comment thread here.",
    commentNotFound: "Comment not found.",
    errorEnterEmail: "Please enter your email address.",
    errorVerifyCode: "Please enter the 6-digit code.",
    resetLinkSent: "If that email is registered, we have sent a password reset link. Please check your inbox.",
    forgotPasswordSubtitle: "Enter your email address and we'll send you a link to reset your password.",
    setNewPasswordSubtitle: "Please create a new password for your account.",
    passwordResetSuccess: "Password reset successfully!",
    emailVerifiedSuccess: "Email verified! Redirecting to login...",
    replyToUser: "Replying to",
    addCommentPlaceholder: "Add a comment…",
    darkTheme: "Dark theme",
    lightTheme: "Light theme",
    language: "Language",
    statistics: "Statistics",
    someone: "Someone",
    newNotification: "New notification",
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This week",
    last30Days: "Last 30 days",
    earlier: "Earlier",
  },

  ru: {
    appName: "Pickmatch",
    login: "Войти",
    loggedInAs: "Вы вошли в аккаунт @{username}",
    register: "Регистрация",
    logout: "Выйти",
    dashboard: "Мои альбомы",
    createAlbum: "Новый альбом",

    email: "Email",
    username: "Имя пользователя",
    password: "Пароль",
    alreadyHaveAccount: "Уже есть аккаунт?",
    dontHaveAccount: "Нет аккаунта?",
    loginTitle: "С возвращением",
    loginSubtitle: "Войдите, чтобы продолжить",
    registerTitle: "Создать аккаунт",
    registerSubtitle: "Присоединяйтесь к Pickmatch",

    albumTitle: "Название альбома",
    albumDescription: "Описание (необязательно)",
    uploadPhotos: "Загрузить фото",
    updatePhoto: "Изменить аватар",
    addPhoto: "Добавить аватар",
    removePhoto: "Удалить аватар",
    uploadDrag: "Перетащите фото сюда или нажмите для выбора",
    uploadHint: "JPEG, PNG, WebP",
    maxFileSize: "до 50 МБ на файл",
    albumTitlePlaceholder: "Моя летняя съёмка 2024",
    albumDescriptionPlaceholder: "Расскажите голосующим, о чём этот альбом…",
    publicAccess: "Публичный доступ",
    publicAccessHint: "Разрешить голосующим видеть статистику",
    uploadRejected: "Некоторые файлы отклонены (слишком большие или неверный формат)",
    uploadFailed: "Не удалось загрузить файл",
    retryUpload: "Повторить загрузку",
    removeUpload: "Удалить файл",
    enterAlbumTitle: "Введите название",
    uploadAtLeastOne: "Загрузите хотя бы одно фото или видео",
    albumCreated: "Альбом создан!",
    creatingAlbum: "Создание альбома…",
    createAlbumBtn: "Создать альбом",
    inviteLink: "Ссылка-приглашение",
    copyLink: "Копировать",
    copied: "Скопировано!",
    myAlbums: "Мои альбомы",
    noAlbums: "Альбомов пока нет — создайте первый",
    photos: "фото",
    votes: "голосов",
    viewAnalytics: "Результаты",
    deleteAlbum: "Удалить",
    albumDeleted: "Удалено",
    albumNotFound: "Альбом не найден",
    sharedWithMe: "Поделились со мной",
    sharedBy: "Поделился",
    shareAlbum: "Поделиться альбомом",
    shareWithUser: "Поделиться (имя пользователя или email)",
    shareSuccess: "Альбом открыт",
    revokeAccess: "Отозвать доступ",
    sharedAccess: "Общий доступ",
    noSharedAlbums: "C вами ещё не поделились альбомами",

    swipeHint: "Вправо — нравится · влево — не нравится",
    allDone: "Вы оценили все фото!",
    viewResults: "Посмотреть результаты",
    swipeRemaining: "осталось",

    seeMore: "Подробнее",
    seeLess: "Свернуть",

    winner: "Победитель",
    winnerBadge: "Лучшее фото",
    likes: "Лайки",
    dislikes: "Дизлайки",
    totalVotes: "Голосов",
    likeRate: "Рейтинг",
    globalLikeRate: "Общий рейтинг",
    uniqueVoters: "Голосующих",
    noVotes: "Пока нет голосов",
    analyticsTitle: "Все фото",
    backToAlbums: "Мои альбомы",
    sort: "Сортировка",
    filterBy: "Фильтр",
    sortMostLikes: "Больше лайков",
    sortMostDislikes: "Больше дизлайков",
    gridView: "Сетка",
    listView: "Список",
    shareAnalytics: "Поделиться статистикой",
    shareAnalyticsHint: "Любой, у кого есть эта ссылка, сможет посмотреть результаты альбома после входа.",
    shareLinkCopied: "Ссылка скопирована",
    shareLinkError: "Не удалось получить ссылку. Попробуйте ещё раз.",
    linkManagement: "Управление ссылкой",
    regenerateLink: "Обновить ссылку",
    regenerateLinkConfirm: "Прежняя ссылка перестанет работать сразу. Продолжить?",
    regenerateLinkDone: "Ссылка обновлена",
    regenerateLinkFailed: "Не удалось обновить ссылку",
    needAccessTitle: "Нужен доступ",
    needAccessBody: "Ссылка недействительна или устарела. Попросите владельца альбома поделиться новой.",
    filterByVoter: "Фильтр по голосующему",
    noVoters: "Голосующих пока нет",
    selectVoters: "Выберите голосующих",
    clearFilter: "Сбросить",
    applyFilter: "Применить",
    sortBy: "Сортировка",
    sortLikesDesc: "Больше лайков",
    sortLikesAsc: "Меньше лайков",
    sortDislikesDesc: "Больше дизлайков",
    filterAll: "Все",
    filterLiked: "Только лайки",
    filterDisliked: "Только дизлайки",
    views: "Просмотры",
    voters: "Голосующие",
    reactions: "Реакции",
    noReactions: "Реакций пока нет",
    share: "Поделиться",

    heroTitle: "Выбери лучшее фото.",
    heroSubtitle: "Вправо — нравится, влево — нет. Быстро и удобно!",
    getStarted: "Начать",
    howItWorks: "Как это работает",
    step1Title: "Загрузи альбом",
    step1Desc: "Добавь фотографии и получи ссылку.",
    step2Title: "Поделись и собери голоса",
    step2Desc: "Отправь ссылку своей аудитории.",
    step3Title: "Узнай победителя",
    step3Desc: "Фото с наибольшим числом лайков побеждает!",

    errorGeneric: "Что-то пошло не так. Попробуйте ещё раз.",
    errorNotFound: "Страница не найдена",
    errorAlbumNotFound: "Альбом не найден или ссылка устарела",

    notifications: "Уведомления",
    replies: "Ответы",
    inbox: "Входящие",
    inboxDetails: "Уведомления об активности",
    allCaughtUp: "Отлично, всё прочитано!",
    noNewNotifs: "Сейчас нет новых уведомлений.",
    Comments: "Комментарии",
    recentlyVisited: "Недавно посещённые",
    vote: "Голосовать",
    revote: "Переголосовать",
    noRecentAlbums: "Здесь появятся альбомы, которые вы посещали",
    viewMyComments: "мои комментарии",
    // Dashboard carousel / expanded view
    seeAll: "Показать все",
    searchAlbums: "Поиск альбомов",
    noSearchResults: "Нет альбомов по вашему запросу",
    sortNewest: "Новые",
    sortAlphabetical: "А–Я",
    sortMostVotes: "Больше голосов",
    sortMostRecent: "Недавние",
    rememberMe: "Запомнить меня",
    forgotPassword: "Забыли пароль?",
    backToLogin: "Назад к входу",
    resetPassword: "Сбросить пароль",
    newPassword: "Новый пароль",
    verifyEmailTitle: "Подтвердите email",
    verifyEmailCode: "Введите код",
    verifyAccountBtn: "Подтвердить аккаунт",
    resendCode: "Не получили код? Отправить ещё раз",
    resendCodeTimer: "Отправить повторно через ",
    passwordStrength: "Сложность пароля",
    strengthWeak: "Слабый",
    strengthMedium: "Средний",
    strengthStrong: "Надёжный",
    reqMinLength: "Минимум 8 символов",
    reqUppercase: "Минимум 1 заглавная буква",
    reqSpecial: "Минимум 1 специальный символ",
    notifCommentPhoto: "прокомментировал(-а) фото с альбома",
    notifLikedComment: "оценил(-а) ваш комментарий",
    notifVotedAlbum: "проголосовал(-а) в вашем альбоме",
    notifRepliedComment: "ответил(-а) на ваш комментарий",
    privateAlbumThreadHint: "Это приватный альбом. Вы можете видеть только свои ветки комментариев.",
    commentNotFound: "Комментарий не найден.",
    errorEnterEmail: "Пожалуйста, введите ваш email.",
    errorVerifyCode: "Пожалуйста, введите 6-значный код.",
    resetLinkSent: "Если этот email зарегистрирован, мы отправили ссылку для сброса пароля. Проверьте ваш почтовый ящик.",
    forgotPasswordSubtitle: "Введите ваш email, и мы отправим ссылку для сброса пароля.",
    setNewPasswordSubtitle: "Пожалуйста, создайте новый пароль для вашего аккаунта.",
    passwordResetSuccess: "Пароль успешно сброшен!",
    emailVerifiedSuccess: "Email подтверждён! Перенаправление на вход...",
    replyToUser: "Ответ для",
    addCommentPlaceholder: "Написать комментарий…",
    darkTheme: "Тёмная тема",
    lightTheme: "Светлая тема",
    language: "Язык",
    statistics: "Статистика",
    someone: "Кто-то",
    newNotification: "Новое уведомление",
    today: "Сегодня",
    yesterday: "Вчера",
    thisWeek: "На этой неделе",
    last30Days: "За последние 30 дней",
    earlier: "Ранее",
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(
    () => localStorage.getItem("pickmatch_lang") || "ru"
  );
  const setLanguage = (l) => { setLang(l); localStorage.setItem("pickmatch_lang", l); };
  const t = (key) => T[lang]?.[key] ?? T.en[key] ?? key;
  return (
    <LangContext.Provider value={{ lang, setLanguage, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be inside LangProvider");
  return ctx;
};
